import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";
import NavBar from "./components/NavBar";
import { Container, CssBaseline } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <CssBaseline enableColorScheme />
          <Container
            component="main"
            role="main"
            maxWidth="xl"
            fixed
            // sx={{
            //   bgcolor: "gray",
            //   textAlign: "center",
            // }}
          >
            <NavBar />
            {children}
          </Container>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
